# Generated by Django 5.1 on 2024-08-29 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizresult_submission_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='date_taken',
        ),
    ]
